### ISSUE TITLE
homework completed

### ISSUE THREAD

**Issue by hatelove** [bobo52310/91TDD-day2-homework#1]
well done! 已經用了 behat 就能體會再加測試案例的時候，簡直輕鬆神速。

唯一的建議是可以考慮 production code 出現壞味道或需要重構時，就可以進行重構了。某種程度來說，會讓後面的 production code 加入時更快。

**Comment by bobo52310** [comment]
使用 Behat 添加測試案例的時候真的十分輕鬆愉快，感謝鐵哥(Jace Ju)和我們分享，也謝謝 91哥的建議~
